/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.Test;
import org.monkcommerce.CouponServiceApplication;

import static org.junit.Assert.*;

public class CouponServiceApplicationTest {

}
